apiVersion: batch/v1
kind: Job
metadata:
  name: django-migration
spec:
  template:
    metadata:
      name: django-migration
    spec:
      containers:
        - name: migration
          image: localhost:32000/sample-app:latest
          command: ["python", "manage.py", "migrate"]
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: database-configmap
                  key: database-host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: database-configmap
                  key: database-port
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: database-configmap
                  key: database-name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: database-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: database-password
      restartPolicy: OnFailure
