---
- name: Install Docker
  hosts: docker_server
  become: yes
  tasks:
    - name: Update apt repo and cache
      ansible.builtin.apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Install dependencies
      ansible.builtin.apt:
        pkg:
          - curl
          - ca-certificates

    - name: Create GPG key directory
      ansible.builtin.file:
        path: /ect/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: a+r

    - name: Get architecture
      ansible.builtin.command: dpkg --print-architecture
      register: architecture

    - name: Get Ubuntu codename
      ansible.builtin.shell:
        cmd: . /etc/os-release && echo $VERSION_CODENAME
      register: codename

    - name: Add repository to apt sources
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: "deb [arch={{architecture.stdout}} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{codename.stdout_lines[0]}} stable"
        state: present
        create: yes

    - name: Install Docker
      ansible.builtin.apt:
        update_cache: yes
        force_apt_get: yes
        state: present
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin

    - name: Check Docker running
      ansible.builtin.systemd_service:
        name: docker
        enabled: true
        state: started

    - name: Add User to Docker group
      ansible.builtin.user:
        name: "{{ansible_user}}"
        groups: docker
        append: yes

    - name: Reconnect to Server
      ansible.builtin.meta: reset_connection

- name: Test Docker Pull Image
  hosts: docker_server
  tasks:
    - name: Pull Image
      community.docker.docker_image:
        name: busybox
        source: pull

- name: Start Docker Compose
  hosts: docker_server
  tasks:
    - name: Copy docker compose file
      ansible.builtin.copy:
        src: ./compose.yml
        dest: /home/{{ansible_user}}/compose.yml

    - name: Run Containers
      community.docker.docker_compose_v2:
        project_src: /home/{{ansible_user}}
        state: present
